export const mockProperties = [
  {
    id: 1,
    name: 'ไอดีโอ คิว วิคตอรี่',
    location: 'อนุสาวรีย์ฯ',
    station: 'BTS Victory Monument',
    transitLine: 'BTS สายสีเขียวอ่อน (สายสุขุมวิท) | Light Green Line',
    type: 'condominium',
    status: 'both',
    priceBuy: 7800000,
    priceRent: 38000,
    bedrooms: 1,
    size: 34.5,
    tag: 'HOT CONDOMINIUM FOR SALE',
    lifestyle: 'ใกล้มหาวิทยาลัย',
    roomType: 'duplex',
    imageUrl: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80',
    virtualTour: true,
    brand: 'แสนสิริ (Sansiri)',
    province: 'กรุงเทพ ฯ',
    district: 'ราชเทวี',
    subDistrict: 'ทุ่งพญาไท',
    distance1: '0 meters from BTS Victory Monument',
    distance2: '650 meters from AIR Phaya Thai'
  },
  {
    id: 2,
    name: 'แอชตัน อโศก - พระราม 9',
    location: 'อโศก - พระราม 9',
    station: 'MRT Phra Ram 9',
    transitLine: 'MRT สายสีน้ำเงิน | Blue Line',
    type: 'condominium',
    status: 'both',
    priceBuy: 5150000,
    priceRent: 25000,
    bedrooms: 2,
    size: 42.0,
    tag: 'RECOMMEND',
    lifestyle: 'สระว่ายน้ำ',
    roomType: 'studio',
    imageUrl: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80',
    virtualTour: true,
    brand: 'แสนสิริ (Sansiri)',
    province: 'กรุงเทพ ฯ',
    district: 'ดินแดง',
    subDistrict: 'ดินแดง',
    distance1: '230 meters from MRT Phra Ram 9',
    distance2: ''
  },
  {
    id: 3,
    name: 'ไอดีโอ โมบิ สุขุมวิท อีสต์พอยท์',
    location: 'บางนา',
    station: 'BTS Bang Na',
    transitLine: 'BTS สายสีเขียวอ่อน (สายสุขุมวิท) | Light Green Line',
    type: 'condominium',
    status: 'both',
    priceBuy: 2880000,
    priceRent: 12000,
    bedrooms: 1,
    size: 28.0,
    tag: 'HOT CONDOMINIUM FOR RENT',
    lifestyle: 'ใกล้ห้างสรรพสินค้า',
    roomType: 'studio',
    imageUrl: 'https://images.unsplash.com/photo-1600607687931-cebf12f45cc3?w=800&q=80',
    virtualTour: false,
    brand: 'ออริจิ้น พร็อพเพอร์ตี้ (Origin Property)',
    province: 'กรุงเทพ ฯ',
    district: 'บางนา',
    subDistrict: 'บางนา',
    distance1: '250 meters from BTS Bang Na',
    distance2: ''
  },
  {
    id: 4,
    name: 'นันทวัน พระราม 9',
    location: 'พระราม 9',
    station: 'MRT Si Kritha',
    transitLine: 'MRT สายสีเหลือง | Yellow Line',
    type: 'house',
    status: 'sale',
    priceBuy: 25000000,
    priceRent: 0,
    bedrooms: 4,
    size: 300.0,
    tag: 'HOUSE',
    lifestyle: 'เลี้ยงสัตว์ได้',
    roomType: 'penthouse',
    imageUrl: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80',
    virtualTour: true,
    brand: 'แลนด์ แอนด์ เฮ้าส์ (Land & Houses)',
    province: 'กรุงเทพ ฯ',
    district: 'บางกะปิ',
    subDistrict: 'หัวหมาก',
    distance1: '800 meters from MRT Si Kritha',
    distance2: '1.2 km from ARL Hua Mak'
  },
  {
    id: 5,
    name: 'พลีโน่ สาทร-สุขสวัสดิ์',
    location: 'สุขสวัสดิ์',
    station: 'MRT Bang Pakok',
    transitLine: 'MRT สายสีม่วง | Purple Line',
    type: 'townhome',
    status: 'sale',
    priceBuy: 4800000,
    priceRent: 0,
    bedrooms: 3,
    size: 130.0,
    tag: 'TOWN HOME',
    lifestyle: 'รปภ. 24 ชม.',
    roomType: 'duplex',
    imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80',
    virtualTour: false,
    brand: 'เอพี ไทยแลนด์ (AP Thailand)',
    province: 'กรุงเทพ ฯ',
    district: 'ราษฎร์บูรณะ',
    subDistrict: 'บางปะกอก',
    distance1: '2.5 km from MRT Bang Pakok',
    distance2: ''
  },
  {
    id: 6,
    name: 'โคโค่ พาร์ค พระราม 4',
    location: 'คลองเตย',
    station: 'MRT Khlong Toei',
    transitLine: 'MRT สายสีน้ำเงิน | Blue Line',
    type: 'condominium',
    status: 'both',
    priceBuy: 6800000,
    priceRent: 24000,
    bedrooms: 1,
    size: 31.5,
    tag: 'HOT CONDOMINIUM FOR SALE',
    lifestyle: 'ฟิตเนส 24 ชม.',
    roomType: 'studio',
    imageUrl: 'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?w=800&q=80',
    virtualTour: true,
    brand: 'ออริจิ้น พร็อพเพอร์ตี้ (Origin Property)',
    province: 'กรุงเทพ ฯ',
    district: 'คลองเตย',
    subDistrict: 'คลองเตย',
    distance1: '0 meters from MRT Khlong Toei',
    distance2: ''
  },
  {
    id: 7,
    name: 'เดอะ ลุมพินี 24',
    location: 'สุขุมวิท 24',
    station: 'BTS Phrom Phong',
    transitLine: 'BTS สายสีเขียวอ่อน (สายสุขุมวิท) | Light Green Line',
    type: 'condominium',
    status: 'rent',
    priceBuy: 0,
    priceRent: 45000,
    bedrooms: 2,
    size: 65.0,
    tag: 'RECOMMEND',
    lifestyle: 'เลี้ยงสัตว์ได้',
    roomType: 'duplex',
    imageUrl: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&q=80',
    virtualTour: true,
    brand: 'แสนสิริ (Sansiri)',
    province: 'กรุงเทพ ฯ',
    district: 'คลองเตย',
    subDistrict: 'คลองตัน',
    distance1: '800 meters from BTS Phrom Phong',
    distance2: ''
  },
  {
    id: 8,
    name: 'เอพี เดอะ ซิตี้',
    location: 'พหลโยธิน',
    station: 'BTS Phahon Yothin 24',
    transitLine: 'BTS สายสีเขียวอ่อน (สายสุขุมวิท) | Light Green Line',
    type: 'house',
    status: 'both',
    priceBuy: 15000000,
    priceRent: 60000,
    bedrooms: 3,
    size: 150.0,
    tag: 'HOUSE',
    lifestyle: 'รปภ. 24 ชม.',
    roomType: 'penthouse',
    imageUrl: 'https://images.unsplash.com/photo-1600573472550-8090b5e0745e?w=800&q=80',
    virtualTour: false,
    brand: 'เอพี ไทยแลนด์ (AP Thailand)',
    province: 'กรุงเทพ ฯ',
    district: 'จตุจักร',
    subDistrict: 'จตุจักร',
    distance1: '1.5 km from BTS Phahon Yothin 24',
    distance2: ''
  },
  {
    id: 9,
    name: 'ศุภาลัย ไพร์ม',
    location: 'พระราม 9',
    station: 'MRT Phra Ram 9',
    transitLine: 'MRT สายสีน้ำเงิน | Blue Line',
    type: 'condominium',
    status: 'rent',
    priceBuy: 0,
    priceRent: 15000,
    bedrooms: 1,
    size: 32.0,
    tag: 'HOT CONDOMINIUM FOR RENT',
    lifestyle: 'ฟิตเนส 24 ชม.',
    roomType: 'studio',
    imageUrl: 'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&q=80',
    virtualTour: true,
    brand: 'ศุภาลัย (Supalai)',
    province: 'กรุงเทพ ฯ',
    district: 'ห้วยขวาง',
    subDistrict: 'ห้วยขวาง',
    distance1: '500 meters from MRT Phra Ram 9',
    distance2: ''
  },
  {
    id: 10,
    name: 'คัลเจอร์ จุฬา',
    location: 'สามย่าน - จุฬา',
    station: 'MRT Sam Yan',
    transitLine: 'MRT สายสีน้ำเงิน | Blue Line',
    type: 'condominium',
    status: 'sale',
    priceBuy: 7490000,
    priceRent: 0,
    bedrooms: 1,
    size: 34.5,
    tag: 'HOT CONDOMINIUM FOR SALE',
    lifestyle: 'ใกล้มหาวิทยาลัย',
    roomType: 'duplex',
    imageUrl: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=800&q=80',
    virtualTour: true,
    brand: 'ออริจิ้น พร็อพเพอร์ตี้ (Origin Property)',
    province: 'กรุงเทพ ฯ',
    district: 'ปทุมวัน',
    subDistrict: 'วังใหม่',
    distance1: '350 meters from MRT Sam Yan',
    distance2: '400 meters from MRT Si Lom'
  },
  {
    id: 11,
    name: 'โกลเด้น ทาวน์ สุขสวัสดิ์',
    location: 'สุขสวัสดิ์',
    station: 'MRT Phra Pradaeng',
    transitLine: 'MRT สายสีม่วง | Purple Line',
    type: 'townhome',
    status: 'both',
    priceBuy: 3500000,
    priceRent: 15000,
    bedrooms: 3,
    size: 110.0,
    tag: 'TOWN HOME',
    lifestyle: 'ใกล้ร้านสะดวกซื้อ',
    roomType: 'duplex',
    imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80',
    virtualTour: false,
    brand: 'เฟรเซอร์ส พร็อพเพอร์ตี้ ประเทศไทย (Frasers Property Thailand)',
    province: 'สมุทรปราการ',
    district: 'พระสมุทรเจดีย์',
    subDistrict: 'ในคลองบางปลากด',
    distance1: '2.0 km from MRT Phra Pradaeng',
    distance2: ''
  },
  {
    id: 12,
    name: 'เดอะ เรสซิเดนซ์ 38',
    location: 'ทองหล่อ',
    station: 'BTS Thong Lo',
    transitLine: 'BTS สายสีเขียวอ่อน (สายสุขุมวิท) | Light Green Line',
    type: 'condominium',
    status: 'sale',
    priceBuy: 18900000,
    priceRent: 0,
    bedrooms: 2,
    size: 78.0,
    tag: 'RECOMMEND',
    lifestyle: 'สระว่ายน้ำ',
    roomType: 'penthouse',
    imageUrl: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80',
    virtualTour: true,
    brand: 'แสนสิริ (Sansiri)',
    province: 'กรุงเทพ ฯ',
    district: 'วัฒนา',
    subDistrict: 'คลองตันเหนือ',
    distance1: '400 meters from BTS Thong Lo',
    distance2: ''
  },
  {
    id: 13,
    name: 'ศาลาแดง วัน',
    location: 'สีลม',
    station: 'BTS Sala Daeng',
    transitLine: 'BTS สีเขียวเข้ม (สายสีลม) | Green Line (Silom Line)',
    type: 'condominium',
    status: 'both',
    priceBuy: 32000000,
    priceRent: 110000,
    bedrooms: 2,
    size: 110.0,
    tag: 'RECOMMEND',
    lifestyle: 'สระว่ายน้ำ',
    roomType: 'penthouse',
    imageUrl: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80',
    virtualTour: true,
    brand: 'เอสซี แอสเซท (SC Asset)',
    province: 'กรุงเทพ ฯ',
    district: 'บางรัก',
    subDistrict: 'สีลม',
    distance1: '450 meters from BTS Sala Daeng',
    distance2: '350 meters from MRT Si Lom'
  },
  {
    id: 14,
    name: 'เคฟ ทาวน์ สเปซ',
    location: 'รังสิต',
    station: 'SRT Thammasat University-Rangsit',
    transitLine: 'SRT สายสีแดง | Red Line Commuter Train',
    type: 'condominium',
    status: 'rent',
    priceBuy: 0,
    priceRent: 9000,
    bedrooms: 1,
    size: 24.0,
    tag: 'HOT CONDOMINIUM FOR RENT',
    lifestyle: 'ใกล้มหาวิทยาลัย',
    roomType: 'studio',
    imageUrl: 'https://images.unsplash.com/photo-1600607687931-cebf12f45cc3?w=800&q=80',
    virtualTour: false,
    brand: 'แอสเซทไวส์ (Asset Wise)',
    province: 'ปทุมธานี',
    district: 'คลองหลวง',
    subDistrict: 'คลองหนึ่ง',
    distance1: '1.2 km from SRT Thammasat University',
    distance2: ''
  },
  {
    id: 15,
    name: 'เซนโทร บางนา',
    location: 'บางนา',
    station: 'BTS Bang Na',
    transitLine: 'BTS สายสีเขียวอ่อน (สายสุขุมวิท) | Light Green Line',
    type: 'house',
    status: 'sale',
    priceBuy: 12000000,
    priceRent: 0,
    bedrooms: 4,
    size: 200.0,
    tag: 'HOUSE',
    lifestyle: 'เลี้ยงสัตว์ได้',
    roomType: 'penthouse',
    imageUrl: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80',
    virtualTour: true,
    brand: 'เอพี ไทยแลนด์ (AP Thailand)',
    province: 'กรุงเทพ ฯ',
    district: 'บางนา',
    subDistrict: 'บางนา',
    distance1: '3.0 km from BTS Bang Na',
    distance2: ''
  },
  {
    id: 16,
    name: 'ดิ เอส อโศก',
    location: 'อโศก',
    station: 'MRT Sukhumvit',
    transitLine: 'MRT สายสีน้ำเงิน | Blue Line',
    type: 'condominium',
    status: 'both',
    priceBuy: 11000000,
    priceRent: 45000,
    bedrooms: 1,
    size: 44.0,
    tag: 'HOT CONDOMINIUM FOR SALE',
    lifestyle: 'ใกล้ห้างสรรพสินค้า',
    roomType: 'studio',
    imageUrl: 'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?w=800&q=80',
    virtualTour: false,
    brand: 'สิงห์ เอสเตท (Singha Estate)',
    province: 'กรุงเทพ ฯ',
    district: 'วัฒนา',
    subDistrict: 'คลองเตยเหนือ',
    distance1: '350 meters from MRT Sukhumvit',
    distance2: '400 meters from BTS Asok'
  },
  {
    id: 17,
    name: 'โมดิซ ไรห์ม รามคำแหง',
    location: 'รามคำแหง',
    station: 'ARL Ramkhamhaeng',
    transitLine: 'ARL แอร์พอร์ต เรล ลิงก์ | Airport Rail Link',
    type: 'condominium',
    status: 'rent',
    priceBuy: 0,
    priceRent: 12000,
    bedrooms: 1,
    size: 28.0,
    tag: 'HOT CONDOMINIUM FOR RENT',
    lifestyle: 'ใกล้มหาวิทยาลัย',
    roomType: 'studio',
    imageUrl: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&q=80',
    virtualTour: true,
    brand: 'แอสเซทไวส์ (Asset Wise)',
    province: 'กรุงเทพ ฯ',
    district: 'บางกะปิ',
    subDistrict: 'บางกะปิ',
    distance1: '150 meters from MRT Ramkhamhaeng',
    distance2: ''
  },
  {
    id: 18,
    name: 'พลัม คอนโด เซ็นทรัล สเตชั่น',
    location: 'เวสต์เกต',
    station: 'MRT Talad Bang Yai',
    transitLine: 'MRT สายสีม่วง | Purple Line',
    type: 'condominium',
    status: 'both',
    priceBuy: 1900000,
    priceRent: 7500,
    bedrooms: 1,
    size: 26.0,
    tag: 'HOT CONDOMINIUM FOR SALE',
    lifestyle: 'ใกล้ห้างสรรพสินค้า',
    roomType: 'studio',
    imageUrl: 'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&q=80',
    virtualTour: true,
    brand: 'พฤกษา เรียลเอสเตท (Pruksa Real Estate)',
    province: 'นนทบุรี',
    district: 'บางใหญ่',
    subDistrict: 'บางใหญ่',
    distance1: '400 meters from MRT Talad Bang Yai',
    distance2: ''
  },
  {
    id: 19,
    name: 'บันยันทรี เรสซิเดนซ์',
    location: 'ริมแม่น้ำเจ้าพระยา',
    station: 'BTS Saphan Taksin',
    transitLine: 'BTS สีเขียวเข้ม (สายสีลม) | Green Line (Silom Line)',
    type: 'condominium',
    status: 'sale',
    priceBuy: 45000000,
    priceRent: 0,
    bedrooms: 2,
    size: 120.0,
    tag: 'RECOMMEND',
    lifestyle: 'สระว่ายน้ำ',
    roomType: 'penthouse',
    imageUrl: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=800&q=80',
    virtualTour: true,
    brand: 'สิงห์ เอสเตท (Singha Estate)',
    province: 'กรุงเทพ ฯ',
    district: 'คลองสาน',
    subDistrict: 'คลองสาน',
    distance1: '1.0 km from BTS Saphan Taksin',
    distance2: 'Boat shuttle service available'
  },
  {
    id: 20,
    name: 'พาร์ค ออริจิ้น พร้อมพงษ์',
    location: 'พร้อมพงษ์',
    station: 'BTS Phrom Phong',
    transitLine: 'BTS สายสีเขียวอ่อน (สายสุขุมวิท) | Light Green Line',
    type: 'condominium',
    status: 'both',
    priceBuy: 14000000,
    priceRent: 55000,
    bedrooms: 2,
    size: 55.0,
    tag: 'RECOMMEND',
    lifestyle: 'ใกล้ห้างสรรพสินค้า',
    roomType: 'duplex',
    imageUrl: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80',
    virtualTour: true,
    brand: 'ออริจิ้น พร็อพเพอร์ตี้ (Origin Property)',
    province: 'กรุงเทพ ฯ',
    district: 'คลองเตย',
    subDistrict: 'คลองเตย',
    distance1: '600 meters from BTS Phrom Phong',
    distance2: ''
  },
  {
    id: 21,
    name: 'ศุภาลัย เวอเรนด้า รามคำแหง',
    location: 'รามคำแหง',
    station: 'MRT Mahat Thai',
    transitLine: 'MRT สายสีเหลือง | Yellow Line',
    type: 'condominium',
    status: 'both',
    priceBuy: 2200000,
    priceRent: 8500,
    bedrooms: 1,
    size: 30.0,
    tag: 'HOT CONDOMINIUM FOR SALE',
    lifestyle: 'ใกล้ร้านสะดวกซื้อ',
    roomType: 'studio',
    imageUrl: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80',
    virtualTour: true,
    brand: 'ศุภาลัย (Supalai)',
    province: 'กรุงเทพ ฯ',
    district: 'บางกะปิ',
    subDistrict: 'บางกะปิ',
    distance1: '300 meters from MRT Mahat Thai',
    distance2: ''
  }
];
